- src/SFA.DAS.Reservations.Web/AppStart/AuthenticationProviderExtensions.cs
- src/SFA.DAS.Reservations.Web/AppStart/AuthorizationService.cs
- src/SFA.DAS.Reservations.Web/AppStart/Configuration.cs
- src/SFA.DAS.Reservations.Web/Controllers/HomeController.cs
- src/SFA.DAS.Reservations.Web/Controllers/ProviderReservationsController.cs
- src/SFA.DAS.Reservations.Web/Infrastructure/EmployerAccountAuthorizationHandler.cs
- src/SFA.DAS.Reservations.Web/Infrastructure/ProviderAuthorizationHandler.cs
- src/SFA.DAS.Reservations.Web/Infrastructure/ProviderUkPrnRequirement.cs
- src/SFA.DAS.Reservations.Web/Infrastructure/RouteValues.cs
- src/SFA.DAS.Reservations.Web/Startup.cs
- src/SFA.DAS.Reservations.Web/Views/Home/Index.cshtml
- src/SFA.DAS.Reservations.Web/Views/ProviderReservations/Index.cshtml
- src/SFA.DAS.Reservations.Web/Views/Shared/_CookieConsentPartial.cshtml
- src/SFA.DAS.Reservations.Web/Views/Shared/_Layout.cshtml
- src/SFA.DAS.Reservations.Web/Views/Shared/_Navigation.cshtml
- src/SFA.DAS.Reservations.Web/Views/_ViewImports.cshtml
Add endpoints for reservation journey and first draft of content. Implement signout for provider portal
> MF-7 reservations provider

- src/SFA.DAS.Reservations.Web/Views/ProviderReservations/Index.cshtml
> Mf 102 content change start page

- src/SFA.DAS.Reservations.Web/Views/Shared/_CourseSearch.cshtml
Added content for the select list
> MF-103 Content Update

- src/SFA.DAS.Reservations.Application.UnitTests/Reservations/Queries/GetCourses/WhenGettingCourses.cs
- src/SFA.DAS.Reservations.Application/Reservations/Queries/GetReservation/GetReservationQueryHandler.cs
- src/SFA.DAS.Reservations.Domain.UnitTests/Courses/WhenCreatingACourse.cs
- src/SFA.DAS.Reservations.Domain/Courses/Course.cs
- src/SFA.DAS.Reservations.Web/Views/Reservations/Confirmation.cshtml
Display Unknown when no course is selected
> Mf 106 display unknown when course not selected

- src/SFA.DAS.Reservations.Web/Views/Reservations/ApprenticeshipTraining.cshtml
- src/SFA.DAS.Reservations.Web/Views/Shared/_Layout.cshtml
> Mf 56 add details element apprenticeship training page

- src/SFA.DAS.Reservations.Domain/Interfaces/IExternalUrlHelper.cs
- src/SFA.DAS.Reservations.Infrastructure.UnitTests/TagHelpers/WhenConstructingTheExternalUrl.cs
- src/SFA.DAS.Reservations.Infrastructure/TagHelpers/ProviderExternalUrlHelper.cs
- src/SFA.DAS.Reservations.Web/AppStart/AuthenticationProviderExtensions.cs
- src/SFA.DAS.Reservations.Web/Infrastructure/ProviderClaims.cs
- src/SFA.DAS.Reservations.Web/Startup.cs
- src/SFA.DAS.Reservations.Web/TagHelpers/UrlHelperExtensions.cs
- src/SFA.DAS.Reservations.Web/Views/Shared/_Layout.cshtml
- src/SFA.DAS.Reservations.Web/Views/Shared/_Navigation.cshtml
- src/SFA.DAS.Reservations.Web/Views/Shared/_SubNavigation.cshtml
- src/SFA.DAS.Reservations.Web/Views/_ViewImports.cshtml
Ready to review - pending front end review from @jamesmking
> MF-133 provider navigation

- src/SFA.DAS.Reservations.Web/Views/Reservations/ProviderManage.cshtml
> MF-84 provider buttons

- src/SFA.DAS.Reservations.Web/Views/Reservations/EmployerManage.cshtml
> MF-88 employer add apprentice

- src/SFA.DAS.Reservations.Web.UnitTests/Employers/WhenViewingTheStartPage.cs
- src/SFA.DAS.Reservations.Web/Controllers/EmployerReservationsController.cs
- src/SFA.DAS.Reservations.Web/Views/EmployerReservations/EmployerFundingPaused.cshtml
- src/SFA.DAS.Reservations.Web/appsettings.json
Mf 127 funding paused employer
> Mf 127 funding paused employer

- src/SFA.DAS.Reservations.Infrastructure.UnitTests/Services/EmployerAccountService/WhenCallingGetEmployerIdentifiers.cs
fixes the transient errors we sometimes see.
> Fix intermittent failing tests.

- src/SFA.DAS.Reservations.Web.UnitTests/Reservations/WhenCallingGetSelectReservation.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Reservations/WhenCallingPostSelectReservation.cs
- src/SFA.DAS.Reservations.Web/Controllers/ReservationsController.cs
- src/SFA.DAS.Reservations.Web/Models/SelectReservationViewModel.cs
- src/SFA.DAS.Reservations.Web/Views/Reservations/ProviderSelect.cshtml
The back link on the select reservation journey now goes back to the
cohort details page
> MF-213 - Add backlink from SelectReservation

- src/SFA.DAS.Reservations.Web/AppStart/AuthenticationProviderExtensions.cs
Added chunking cookie manager to deal with issue of large cookie sizes
being blocked in certain browsers
> MF-226 Add ChunkingCookieManager

- src/SFA.DAS.Reservations.Web.UnitTests/Filters/WhenIToggleAFeature.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Infrastructure/EmployerAccountAuthorizationHandlerTests/WhenDeterminingIsAuthorised.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Infrastructure/EmployerAccountAuthorizationHandlerTests/WhenHandlingRequest.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Infrastructure/HasEmployerViewerUserRoleOrIsProviderTests/WhenHandlingRequest.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Infrastructure/HasProviderOrEmployerAccountAuthorisationHandlerTests/WhenHandlingRequest.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Infrastructure/ProviderAuthorizationHandlerTests/WhenDeterminingIsAuthorised.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Infrastructure/ProviderAuthorizationHandlerTests/WhenHandlingRequest.cs
- src/SFA.DAS.Reservations.Web/Infrastructure/EmployerAccountAuthorizationHandler.cs
This is for the MF-247 task as is limited to mainly the authorization code
> MF-247 - Unit test coverage review

- src/SFA.DAS.Reservations.Web/AppStart/ProviderRelationshipsExtensions.cs
- src/SFA.DAS.Reservations.Web/Startup.cs
- src/SFA.DAS.Reservations.Web/Views/Shared/NoPermissions.cshtml
Corrected the using statmenet being used for provider relationships DI
registration. Also corrected incorret CSS class on the no permissions
back link for providers
> MF-271 Correct using statement

- src/SFA.DAS.Reservations.Web/Views/ProviderReservations/ChooseEmployer.cshtml
- src/SFA.DAS.Reservations.Web/Views/ProviderReservations/ConfirmEmployer.cshtml
- src/SFA.DAS.Reservations.Web/Views/Reservations/ProviderReview.cshtml
Updated content for provider journey when choosing an employer, all instances of it referring to secure funding have been changed to reserve
> MF-288 - Change secure to reserve employer select journey

- src/SFA.DAS.Reservations.Web.UnitTests/Employers/WhenViewingCourseGuidance.cs
- src/SFA.DAS.Reservations.Web/Controllers/EmployerReservationsController.cs
- src/SFA.DAS.Reservations.Web/Infrastructure/RouteNames.cs
- src/SFA.DAS.Reservations.Web/Models/CourseGuidanceViewModel.cs
- src/SFA.DAS.Reservations.Web/Views/EmployerReservations/CourseGuidance.cshtml
- src/SFA.DAS.Reservations.Web/appsettings.json
Added new page to help users that dont know which course to select
> MF-285 - Add new course guidance page

- src/SFA.DAS.Reservations.Application.UnitTests/Reservations/Commands/CreateReservation/WhenCreatingANewReservation.cs
- src/SFA.DAS.Reservations.Application.UnitTests/Reservations/Commands/CreateReservationLevyEmployer/WhenCreatingANewReservationForLevyEmployer.cs
- src/SFA.DAS.Reservations.Application.UnitTests/Reservations/Services/WhenCallingReservationService.cs
- src/SFA.DAS.Reservations.Application/Reservations/Commands/CreateReservation/CreateReservationCommand.cs
- src/SFA.DAS.Reservations.Application/Reservations/Commands/CreateReservation/CreateReservationCommandHandler.cs
- src/SFA.DAS.Reservations.Application/Reservations/Commands/CreateReservationLevyEmployer/CreateReservationLevyEmployerCommand.cs
- src/SFA.DAS.Reservations.Application/Reservations/Commands/CreateReservationLevyEmployer/CreateReservationLevyEmployerCommandHandler.cs
- src/SFA.DAS.Reservations.Application/Reservations/Services/IReservationService.cs
- src/SFA.DAS.Reservations.Application/Reservations/Services/ReservationService.cs
- src/SFA.DAS.Reservations.Domain.UnitTests/ReservationsApi/WhenCreatingAReservationApiRequest.cs
- src/SFA.DAS.Reservations.Domain/Reservations/Api/ReservationApiRequest.cs
- src/SFA.DAS.Reservations.Web.AcceptanceTests/Infrastructure/TestData.cs
- src/SFA.DAS.Reservations.Web.AcceptanceTests/Steps/EmployerSelectReservationSteps.cs
- src/SFA.DAS.Reservations.Web.AcceptanceTests/Steps/ReservationSteps.cs
- src/SFA.DAS.Reservations.Web.AcceptanceTests/Steps/StepsBase.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Reservations/WhenCallingGetSelectReservation.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Reservations/WhenCallingPostReview.cs
- src/SFA.DAS.Reservations.Web/Controllers/ReservationsController.cs
- src/SFA.DAS.Reservations.Web/Controllers/SelectReservationsController.cs
The user id is now stored against the reservation through the employer journey
> MF-305 store user id

- src/SFA.DAS.Reservations.Application.UnitTests/Reservations/Commands/DeleteReservation/WhenDeletingAReservation.cs
- src/SFA.DAS.Reservations.Application/Reservations/Commands/DeleteReservation/DeleteReservationCommand.cs
- src/SFA.DAS.Reservations.Application/Reservations/Commands/DeleteReservation/DeleteReservationCommandHandler.cs
- src/SFA.DAS.Reservations.Domain.UnitTests/ReservationsApi/WhenCreatingAReservationApiRequest.cs
- src/SFA.DAS.Reservations.Domain/Reservations/Api/ReservationApiRequest.cs
- src/SFA.DAS.Reservations.Infrastructure/Api/ApiClientBase.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Manage/WhenCallingPostDelete.cs
- src/SFA.DAS.Reservations.Web/Controllers/ManageReservationsController.cs
Update web to reflect changes in api for determining whether the delete request has come from the employer or the provider.
> MF-34 reservation deleted notification

- src/SFA.DAS.Reservations.Domain.UnitTests/ReservationsApi/WhenCreatingAReservationSearchApiRequest.cs
- src/SFA.DAS.Reservations.Domain/Reservations/Api/SearchReservationsApiRequest.cs
- src/SFA.DAS.Reservations.Domain/Reservations/ReservationFilter.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Manage/WhenCallingGetProviderManage.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Models/WhenCastingManageReservationsFilterModelToDomainType.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Models/WhenGettingPageLinks.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Models/WhenGettingPagedRecordsFrom.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Models/WhenGettingPagedRecordsTo.cs
- src/SFA.DAS.Reservations.Web/Controllers/ManageReservationsController.cs
- src/SFA.DAS.Reservations.Web/Models/ManageReservationsFilterModel.cs
- src/SFA.DAS.Reservations.Web/Models/ManageViewModel.cs
- src/SFA.DAS.Reservations.Web/Views/ManageReservations/ProviderManage.cshtml
PR is based on MF-159 in order to easily see the diff for this branch.
> MF-318 paging

- azure/template.json
- src/SFA.DAS.Reservations.Web.AcceptanceTests/Tests/WhenViewingTheReservationServiceAsNonLevyEmployer.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Models/WhenBuildingError403ViewModel.cs
- src/SFA.DAS.Reservations.Web.UnitTests/Providers/WhenVisitingTheAccessDeniedPage.cs
- src/SFA.DAS.Reservations.Web/Controllers/ErrorController.cs
- src/SFA.DAS.Reservations.Web/Models/Error403ViewModel.cs
- src/SFA.DAS.Reservations.Web/Views/Error/AccessDenied.cshtml
- src/SFA.DAS.Reservations.Web/appsettings.json
403 Forbidden Error Page with content relevant to DfESignIn
https://skillsfundingagency.atlassian.net/browse/FAI-906
> FAI-906_Reservations_Amend_Access_Denied

- azure/template.json
- src/SFA.DAS.Reservations.Web.UnitTests/Providers/WhenCallingDashboard.cs
- src/SFA.DAS.Reservations.Web/Controllers/HomeController.cs
- src/SFA.DAS.Reservations.Web/SFA.DAS.Reservations.Web.csproj
- src/SFA.DAS.Reservations.Web/Startup.cs
Commit Details:
1) Update DfESignIn Nuget Package to latest
2) Intercept OpenIdConnect Signout Event with OnSignedOutCallbackRedirect option to destroy the OpenIdConnect Cookie and SignOut the User Auth session
Story: https://skillsfundingagency.atlassian.net/browse/FAI-886
> FAI-886 Return logged off users to the service start screen
